version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fredyprofesor
      POSTGRES_PASSWORD: univalle
      POSTGRES_DB: univalle_db
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tutor@univalle.com
      PGADMIN_DEFAULT_PASSWORD: albaricoque
    volumes:
      - ./private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - '5050:80'
